# Generated by Django 3.2.7 on 2021-09-20 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_book_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ForeignKey(default='unknown', on_delete=django.db.models.deletion.CASCADE, to='core.author'),
        ),
    ]
